### ISSUE TITLE
Determine which font-awesome icons to use for Magician, Routine, and Material placeholders. Create CSS to style icons appropriately.

### ISSUE THREAD

**Issue by davidkneely** [PlayWithMagic/PlayWithMagic.org#199] opened 2015-05-05 00:25 UTC
http://fortawesome.github.io/Font-Awesome/icons/

**Comment by davidkneely** [comment] 2015-05-05 00:26
Currently just using placeholder image "card-rainbow.jpg"

**Comment by pkarjala** [comment] 2015-05-05 02:36
Duplicate of #189.

**Closed as completed** 2015-05-05 02:36 UTC
Labels: bug, help wanted, Design, Magician, Routine, Material
